### ISSUE TITLE
Website languages dropdown is blurred

### ISSUE THREAD

**Issue by nicosh** [conventional-commits/conventionalcommits.org#396]
In Google Chrome 92 the items in languages dropdown are blurred :   

![screen](https://user-images.githubusercontent.com/8511928/132015365-35e7ad70-0302-43f7-8add-de1072fdee31.jpg)

```
.dropdown__option a {
    text-transform: inherit;
}
```
Seems to fix the bug.

**Comment by damianopetrungaro** [comment]
@lorenzodianni do you have time for this?

**Comment by lorenzodianni** [comment]
Unfortunately `text-transform: inherit;` will change the text behavior from Capitalized to PASCALCASE
Anyway a don't see anymore the bug (Chrome v93), do you?

The problem could be the antialias and the computed font set to `12.8px`. We could round up to `13px` and should works without touch the text-transform

But in any case, if the problem is auto-resolved in v93, i don't think we need to apply anything. What do you think @damianopetrungaro?

**Comment by nicosh** [comment]
@lorenzodianni, i still see the bug (Chrome v93). 
Btw i dont think the problem is the `text-transform` property (removing `overflow: auto;` from parent `ul` also seems to remove the blur) rather i think is a Chrome/Windows bug (i have the same behaviour with edge, tested on 2 different computers).

**Comment by damianopetrungaro** [comment]
@nicosh should be fixed, let me know if it is still not fixed re-opening the issue :D

**Comment by TinF9** [comment]
Hello all
The issue seems to be back (Chrome v 112).

One option that appears to fix it is reducing the `font-size` to `12px` on `.dropdown__options`.

Another option is removing `overflow: auto` (removing the scrollbar) on `.dropdown__options`.

On mobile/tablet it is already looking all right.

@damianopetrungaro
